### PR TITLE
Review CI artifacts

### LINKED ISSUE #2618: Review CI artifacts
Need to review if artifacts saved during CI workflows are still required

### PR DESCRIPTION
**Pull request by elglup**
## Related issue

closes #2618 

## Overview

 Remove unrequired artifacts from build & test workflows

## Reason

Workflow housekeeping

## Work carried out

- [x] Removed xml output from lint react component library step
- [x] Removed redundant package eslint-junit 
- [x] Removed xml output from lint css framework step

### CODE REVIEW

**Review by m7kvqbe1 — APPROVED** [review]
Nice LGTM!

**Review by jpveooys — COMMENTED** [review]
Looks good! :+1: 

Are we able to get rid of the `lint:ci` entry from `packages/react-component-library/package.json` now?

(Just noticed there's one in `packages/design-tokens/package.json` too...)

**Comment by elglup** [comment]
> 
> Are we able to get rid of the `lint:ci` entry from `packages/react-component-library/package.json` now?
> 
> (Just noticed there's one in `packages/design-tokens/package.json` too...)

👍 Yes can add this in

**Review by jpveooys — APPROVED** [review]
Nice one :+1:

**Pull request merged**
