### PR TITLE
fix(SelectE): Add drop shadow

### LINKED ISSUE #2887: Add drop shadow to `SelectE`
As highlighted in [review](https://github.com/defencedigital/mod-uk-design-system/pull/2838#issuecomment-984776211), drop shadow needs adding to the outer wrapper.

### PR DESCRIPTION
**Pull request by thyhjwb6**
## Related issue
Fixes #2887 

## Overview
Adds a drop shadow to `SelectE`.

## Link to preview
https://selecte-drop-shadow.netlify.app/?path=/story/select-experimental--default

## Work carried out
- [x] Add drop shadow

## Screenshot
Screenshot 2021-12-10 at 13 50 09

### CODE REVIEW

**Review by jpveooys — APPROVED** [review]
I reckon it might need to be made a little bit less intense though (will leave it to k9dh3zij to confirm :slightly_smiling_face: )

**Comment by thyhjwb6** [comment]
@jpveooys @k9dh3zij drop shadow has been updated https://selecte-drop-shadow.netlify.app/?path=/story/select-experimental--default

Screenshot 2021-12-14 at 11 15 25

**Comment by k9dh3zij** [comment]
👍 Perfect, thanks!

**Comment by m7kvqbe1** [comment]
https://github.com/defencedigital/mod-uk-design-system/blob/master/packages/design-tokens/src/tokens/light/shadows.json

Should we be leveraging or at least supplementing design-tokens with these new shadow values?

**Review by m7kvqbe1 — APPROVED** [review]

**Pull request merged**
