### PR TITLE
feat(Forms): Implement baseline CheckboxE and RadioE components

### LINKED ISSUE #2433: Copy existing `Radio` to `RadioE`
> Radio buttons are presented in groups and allow users to choose only one of a predefined set of mutually exclusive options.

- [x] Copy component
- [x] Apply CSS changes
  - [x] Spacing between radio and label
  - [x] ...

There is a separate [RadioGroup](https://github.com/Royal-Navy/design-system/issues/2441) component.

[Design spec](https://docs.google.com/document/d/1V6hTZvG_HZhHixt8ZrC6Yr-_0xzoAR6JoX8zyR2JtUc/edit#heading=h.iv21fotl4v3r)

### LINKED ISSUE #2437: Copy existing `Checkbox` to `CheckboxE`
> Checkboxes allow users to select zero, one, or any number of items from a list.

- [x] Copy component
- [x] Apply CSS changes

[Design spec](https://docs.google.com/document/d/1yXF0wUUvvsH88j9bn-PGc9VD3zr75tAC78uuXfFCoNs/edit#heading=h.cev23oh66p1j)

### PR DESCRIPTION
**Pull request by m7kvqbe1**
## Related issue

Closes #2433 & Closes #2437

## Overview

Implement new `CheckboxE` and `RadioE` components and reach feature parity with legacy.

## Link to preview

https://60e434d9951e89180d34ea6b--ecstatic-snyder-ae81f8.netlify.app

## Work carried out

- [x] Create `CheckboxE` component
- [x] Create `RadioE` component
- [x] Remove previously marked deprecations
- [x] Create and utilise `Fieldset` component
- [x] Conduct cross browser UAT

## Screenshot

Screenshot 2021-06-29 at 09 14 18
Screenshot 2021-06-29 at 09 14 24
Screenshot 2021-06-29 at 09 14 40
Screenshot 2021-06-29 at 09 14 43
Screenshot 2021-06-29 at 09 14 49
Screenshot 2021-06-29 at 09 15 09

## Developer notes

Currently working through some discrepancies in implementation detail between the two implementations.

### CODE REVIEW

**Comment by k9dh3zij** [comment]
Thanks @m7kvqbe1 , here's my feedback:

**Both `CheckboxE` and `RadioE`**

1. Clicking anywhere inside the container but not over the label itself seems to activate it, but does not actually select it.
2. Row height is 48px (including borders). It should be 46px.
3. When in the error state, the inner borders should not turn red or double is size

image

Please note the design spec:
image

4. Error message should be displayed above - not sure if this is part of this ticket?

5. I can't seem to be able to tab properly through the options, but I wonder if that's a Storybook issue? Need to properly test accessibility, but not sure how with Storybook?

**`RadioE` only**

1. The space between the label and the radio circle is 8px - should be 12px
2. The checked radio is using the old style:

image

Please note the design spec:

image

**Comment by m7kvqbe1** [comment]
Screenshot 2021-07-06 at 07 38 09
Screenshot 2021-07-06 at 08 06 33

**Comment by k9dh3zij** [comment]
Thanks for the awesome changes @m7kvqbe1 - one leftover and two new ones:

**Both `CheckboxE` and `RadioE`**

1. The active border should appear in front of default borders

image
image


**`RadioE` only**

2. (this has been fixed for `CheckboxE`) Clicking anywhere inside the container but not over the label itself seems to activate it, but does not actually select it.


https://user-images.githubusercontent.com/73531035/124576104-e751b980-de43-11eb-8825-0e3d0860353b.mov

3.  Grouped Radios in Error state don't display active borders

To reproduce

- go to:

https://60e4025a4dd64e62791eefa2--relaxed-haibt-f4860e.netlify.app/?path=/docs/radioe--default#formik-group

- Click Submit - the second radio group should now be in its error state
- Press Shift+Tab  - this should highlight the second radio group, however nothing is shown. Pressing shift+Tab again highlights the first radio group

Contrast that with the single [`Invalid` radio](https://60e4025a4dd64e62791eefa2--relaxed-haibt-f4860e.netlify.app/?path=/docs/radioe--default#invalid), which changes to active when it gets focus.

**Comment by m7kvqbe1** [comment]
Screenshot 2021-07-06 at 11 39 27

**Comment by k9dh3zij** [comment]
@m7kvqbe1   Thanks for the fixes. A couple of issues with the border design:

1. The error border fix highlighted something I should have caught earlier:

The active border extends outside the component, not inside. Pixel 1 of 3 of the active border is the same as the default border, and the 'extra' 2 pixels are on the outside. See note from the spec below:

image

2. For some reason, on a Mac Chrome 91.0.4472.114 the borders look a bit funny:

image

3. Thanks for fixing the radios. Is there a way to also highlight the radio when the user hovers their mouse over the entire container (the same way it gets highlighted when hovering over the radio area)?

https://user-images.githubusercontent.com/73531035/124593022-0eb18200-de56-11eb-8370-9e29b53794fe.mov

4. The issue with the active border/shadow z-index seems to persist (notice the bottom shadow below)?

image

5. Not sure if this is because of Storybook, but:

- Go [here](https://60e434d9951e89180d34ea6b--ecstatic-snyder-ae81f8.netlify.app/?path=/docs/checkboxe--default#formik-group)
- Click Submit - second group is now in its `error` state
- Press Shift+Tab
- Press space to select an option
- Press space again to deselect it (no options should be selected)
- Click Submit again  - shouldn't the form be in its `error` state again?

**Comment by k9dh3zij** [comment]
Thanks for the latest deployment @m7kvqbe1  - all looking great on my side! 👍

**Review by thyhjwb6 — APPROVED** [review]
👍

**Pull request merged**
