### PR TITLE
Add initial home page content

### PR DESCRIPTION
**Pull request by ghost**
## Related Jira issue:
https://rn-nelson.atlassian.net/browse/EN-673

## Overview

Added a first draft of the home page content.

## Reason

We need to write the content for the homepage of the docsite.

## Work carried out

- [x] Drafted initial content

### CODE REVIEW

**Comment by 09txzS1qs** [comment]
@aavvjg6j I've edited the homepage content - feedback welcome :)

**Comment by 09txzS1qs** [comment]
I'll wait to approve until we discuss.

**Comment by ghost** [comment]
@09txzS1qs I've made a couple of tweaks to shorted the content in the hero banner, and avoid the repeated 'this design system' phrase. See what you think.

**Review by 09txzS1qs — APPROVED** [review]
changes look good.

**Pull request merged**
