### PR TITLE
fix(Fonts): Correct vertical metrics in font files

### LINKED ISSUE #3543: Label text is not vertically middle for `Autocomplete` and `Select` in Firefox
The label text is 1px away from being in the middle in Firefox browser.

### Screenshot
Screenshot 2022-12-07 at 14 12 52

### LINKED ISSUE #3544: Label text is not vertically middle for `Button` in Firefox
Appears to be out by 1px.

### Screenshot
Screenshot 2022-12-07 at 14 16 25

### PR DESCRIPTION
**Pull request by jpveooys**
## Related issue

Resolves #3543 
Resolves #3544

## Overview

This:

- updates the font files to correct their vertical metrics
- removes loading of local versions of Lato, as these are likely to be faulty

## Link to preview

- After: https://red-playground.netlify.app
- Before: https://storybook.design-system.digital.mod.uk

## Reason

Font files contain multiple versions of vertical metrics, and different ones are used depending on the browser and OS combination.

Unfortunately, the existing vertical metrics were causing incorrect and inconsistent positioning (in particular vertical centring) depending on the browser and OS. There also doesn't appear to be any current development on Lato to get it fixed in the original font.

## Work carried out

- [x] Calculate new font vertical metrics
- [x] Generate new font files
- [x] Remove loading of local font files
- [x] Update component library CSS
- [x] Test in Firefox, Chrome on Ubuntu
- [x] Test in Firefox, Chrome and IE on Windows

## Before and after

Taken in Firefox on Ubuntu 22.04.

### Button

button-alignment

### Autocomplete

autocomplete-alignment

## Developer notes

The new metrics were determined using the guide on http://googlefonts.github.io/gf-docs/VerticalMetrics/

The main calculations were:

- caps height = 1433 (from Lato Regular, unfortunately is inconsistent across the weights in Lato)
- units per em = 2000
- typoDescender = -(2000*1.2005 - 1433)/2 = -484
- typoAscender = typoDescender + 1433 = 1917
- A grave yMax = 1867 (Lato Black) (<1917)
- g yMin = -376 (Lato Hairline) (<-484)

A Python script was used to apply the new metrics, a copy of it is at https://gist.github.com/jpveooys/6a650b8a8698655f18665f9263ba0d5a.

Some CSS had to be updated where manual alignment done using padding etc. (including the removal of some IE11-specific values). It's possible downstream apps may need to make similar adjustments if similar manual alignment using `padding-top` etc. had been done.

### CODE REVIEW

**Comment by jpveooys** [comment]
@thyhjwb6 @adamledwards Could you have a look around at https://red-playground.netlify.app/ and check if all is okay in your environments? I haven't been able to test macOS in particular.

**Comment by jpveooys** [comment]
Just having a further look at the values, will push another update in a bit (I don't expect any notable visual changes).

**Comment by jpveooys** [comment]
Made some further tweaks to the font vertical metrics, and also made the TextInput vertical centring more accurate using flexbox (also applies to related components such as Autocomplete).

**Comment by adamledwards** [comment]
Looks good on the mac, I did check `Use_Typo_Metric` currenly `<fsSelection value="00000000 11000000"/> ` value with fonttool because there was no mention of it, in the PR.  Just wanted to confirm with you if that is the correct settings

**Comment by jpveooys** [comment]
Cheers @adamledwards 

[Yep, it should be if the bits are numbered from the right starting from zero.](https://learn.microsoft.com/en-us/typography/opentype/spec/os2#fsselection) I checked FontForge also:

image

**Review by adamledwards — APPROVED** [review]

**Pull request merged**
