### PR TITLE
Feature/button design docs

### PR DESCRIPTION
**Pull request by hxltrhuxze**
## Overview
Added the Button component design documentation, including SVG diagrams.

## Work carried out

- [x] Added the button component design documentation
- [x] Added optimised SVGs for illustrative purposes

## Notes
The development docs are the empty template as they'll need rewriting to match the new format.

### CODE REVIEW

**Comment by 09txzS1qs** [comment]
Who's on the hook to write the dev docs? I've updated the content.

**Comment by hxltrhuxze** [comment]
that'll be @antictor or @m7kvqbe1

**Review by 09txzS1qs — APPROVED** [review]
happy with the design docs content, guessing you'll need someone else to review the CSS.

**Comment by hxltrhuxze** [comment]
It's a minor change of one shade of the primary colours, probably doesn't warrant a review tbh

**Pull request merged**
