### PR TITLE
Feature/EN-742 checkbox component

### PR DESCRIPTION
**Pull request by m7kvqbe1**
## Related Jira issue: 

https://rn-nelson.atlassian.net/browse/EN-742

## Overview

Implement a Formik friendly Checkbox component.

## Reason

>The Checkbox Component is an on/off toggle used in forms. It allows the selection of an arbitrary number of available options at any one time.

## Work carried out

- [x] Implement base component and style (m7kvqbe1)
- [x] Add to Storybook (m7kvqbe1)
- [x] Integrate with Formik library (m7kvqbe1)
- [x] Add automated tests (m7kvqbe1)
- [x] Create developer documentation (m7kvqbe1)
- [x] Adjusted the CSS to match the design comps more closely (hxltrhuxze)
- [x] Added the Design Docs (hxltrhuxze)
- [x] Added related SVG imagery (hxltrhuxze)
- [x] Decouple from Formik (m7kvqbe1)

### CODE REVIEW

**Comment by antictor** [comment]
Have you tested this on IE 11?

**Comment by 09txzS1qs** [comment]
looks good.

**Review by 09txzS1qs — APPROVED** [review]

**Comment by antictor** [comment]
Did this get tested on IE11 yet?

**Comment by m7kvqbe1** [comment]
> Did this get tested on IE11 yet?

Not yet it was still being worked on. I will do this though. Is that our minimum target environment now?

**Pull request merged**
