### PR TITLE
feat: Upgrade React, ReactDOM, styled-components to latest

### PR DESCRIPTION
**Pull request by m7kvqbe1**
## Overview

Upgrade `React`, `ReactDOM` and `styled-components` to latest majors.

## Reason

These dependencies were a major version behind.

## Work carried out

- [x] Remove `React.FC` usage (no longer recommended)
- [x] Upgrade React and ReactDOM to `18.2.0`
- [x] Upgrade styled-components to `6.1.8`
- [x] Fix issues with typings across all packages
- [x] Fix an RDNS reference in the logger
- [x] Upgrade Storybook to latest
- [x] Upgrade RTL to latest
- [x] Add a known unpatched security advisory to audit whitelist
- [x] Correctly mark some props as transient ($) / drop unused
- [x] Update some broken Playwright specs
- [x] Remove reliance on defunct Toast library

## Screenshot

Screenshot 2024-02-15 at 14 07 26

## Developer notes

This is a breaking change! Downstream consumers will need to upgrade their peer dependencies accordingly.

### CODE REVIEW

**Comment by m7kvqbe1** [comment]
Pre-release published to npm registry with _next_ tag `4.0.0-alpha.0`.

**Comment by ghost** [comment]
Error: 
Steps to reproduce
Added DS to a clean next.js install and then added the simple starter from https://design-system.navy.digital.mod.uk/guidance/installation-and-quick-start (which needs updating ;)

```
Error:
  × pragma cannot be set when runtime is automatic
    ╭─[/Users/mark/dev/mod/rnds-upgrade-spike/node_modules/@royalnavy/react-component-library/node_modules/react-toast-notifications/dist/ToastContainer.js:20:1]
 20 │ function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
 21 │
 22 │ function _objectWithoutProperties(obj, keys) { var target = {}; for (var i in obj) { if (keys.indexOf(i) >= 0) continue; if (!Object.prototype.hasOwnProperty.call(obj, i)) continue; target[i] = obj[i]; } return target; }
 23 │ /** @jsx jsx */
    · ───────────────
 24 │
 25 │ var placements = {
 26 │   'top-left': { top: 0, left: 0 },
```

**Comment by m7kvqbe1** [comment]
Pre-release published to npm registry with next tag `4.0.0-alpha.1`.

**Review by ghost — APPROVED** [review]
Epic and long overdue change.
LGTM

**Pull request merged**
