### PR TITLE
Feature/switch component

### PR DESCRIPTION
**Pull request by m7kvqbe1**
## Related issue

https://github.com/Royal-Navy/standards-toolkit/issues/194

## Overview

Implement and document the responsive Switch component.

## Reason

>The switch component is a form component used to record a selection from a number of values. With regards to behaviour, a switch can be thought of like a radio field, allowing a single choice from a small number of options. The different between a switch and radio is presentation, a switch looks similar to a button group.

## Work carried out

- [x] Implement the base Switch functionality
- [x] Add ResponsiveSwitch wrapper component
- [x] Style the base component
- [x] Create adapter for Formik compatibility
- [x] Add automated tests
- [x] Add developer documentation
- [x] Perform UAT down to Chrome 38 (and across multiple devices)
- [x] Re-organise the exports for Formik enhanced components
- [x] Add design documentation
- [x] Finish implementing responsive behaviour

## Developer notes
- ~~Using the CSS framework `color()` helper I seem to be unable to pick the same background.~~
- ~~Awaiting `<Select />` implementation in order to finish adding responsive behaviour @mobile.~~

### CODE REVIEW

**Comment by m7kvqbe1** [comment]
The GIF preview makes the background look lighter than it is - using `color(neutral, 0)`.

**Comment by hxltrhuxze** [comment]
I think I'm gonna have to retweak the active state of the switch ever so slightly. Just realised it's re-rendering itself when the text goes bold, meaning it can potentially throw off other components that are situated next to it.

Maybe just darkening the text with no bold might be ok visually

**Review by antictor — APPROVED** [review]
Only comment is the switches moving around a little when selected

**Comment by m7kvqbe1** [comment]
> Only comment is the switches moving around a little when selected

The gif is slightly out of date - designer has resolved this with a slight style tweak.

**Pull request merged**
