### PR TITLE
Remove Vue Components

### PR DESCRIPTION
**Pull request by antictor**
The Vue components are now very stale and not in sync with the css styles so need to be removed and will be re-created when the need arises.

### CODE REVIEW

**Review by m7kvqbe1 — APPROVED** [review]
Shall we request to have the package removed from the registry to prevent accidental usage / confusion? It's not being and shouldn't be being consumed by anyone.

**Comment by antictor** [comment]
You can't get it removed from the registry.. so it just sits there I'm afraid, like so many others

**Comment by m7kvqbe1** [comment]
> You can't get it removed from the registry.. so it just sits there I'm afraid, like so many others

You can - i've done it before with other packages. You just have to send them a support ticket.

**Comment by m7kvqbe1** [comment]
https://docs.npmjs.com/unpublishing-packages-from-the-registry

**Pull request merged**
